### ISSUE TITLE
정규식 문제

### ISSUE THREAD

**Issue by jms8732** [CSID-DGU/2019-1-CECD2-HOJE-1#3]
현재 reg 폴더에 있는 reg.json에 회사에서 받은 정규식을 사용 했을 시, masking 모듈이 나가는 현상 발생 => 정규식 길이로 인한 것으로 추정

**Comment by TaekWan-Oh** [comment]
boost에서 넘어온 std::regex_match() 함수 문제, 다른 정규표현식 매칭 라이브러리를 사용하거나 새로 작성해야할것으로 보임.

**Comment by TaekWan-Oh** [comment]
regex_match에서는 negative lookbehind(?<!)를 제공해주지 않아 생기는 문제. 현재 마스킹에 사용되는 정규표현식에서 negative lookbehind 제거하니 정상적으로 동작. 정규표현식에서 (?<!)를 대체하여 작성할 필요성이 있음
